name: image_build

on:
  push:
    branches:
      - master
      - main
    tags:
      - v*

env:
  ORG_NAME: wkokolis
  IMAGE_NAME: ghatest

jobs:
  build:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v2

      - name: Build Image
        run: docker build -t $ORG_NAME/$IMAGE_NAME .

      - name: Log in to DockerHub
        run: echo "${{ secrets.WKOKOLIS_DOCKERHUB }}" | docker login -u wkokolis --password-stdin

      - name: Push image
        run: docker push $ORG_NAME/$IMAGE_NAME
