name: image_build

on:
  push:
    branches:
      - master
      - main
    tags:
      - v*

env:
  REGISTRY: ghcr.io
  ORG_NAME: wkokolis
  IMAGE_NAME: ghatest

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Build Image
        run: docker build -t $REGISTRY/$ORG_NAME/$IMAGE_NAME:${GITHUB_SHA::8} .

      - name: 'Get tag from ref'
        id: getTag
        if: contains(github.ref, "refs/tags")
        uses: uses: olegtarasov/get-tag@v2.1
      - name: 'Build tagged image'
        id: tagBuild
        if: contains(github.ref, "refs/tags") 
        run: docker build -t $ORG_NAME/$IMAGE_NAME:${{ steps.getTag.outputs.tag }} .

#      - name: Log in to DockerHub
#        run: echo "${{ secrets.WKOKOLIS_DOCKERHUB }}" | docker login -u wkokolis --password-stdin

#      - name: Log into GitHub container registry
#        run: echo "${{ secrets.MY_TOKEN }}" | docker login https://ghcr.io -u wkokolis --password-stdin

#      - name: Push image
#        run: docker push $REGISTRY/$ORG_NAME/$IMAGE_NAME
