name: Perform Sonarqube scan

on: 
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  sonarqube:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v2
    - name: SonarCloud Scan
      uses: kitabisa/sonarqube-action@v1.1.0
      with:
        host: ${{ secrets.SONARQUBE_HOST }}
        login: ${{ secrets.SONARQUBE_TOKEN }}
        projectKey: "github-actions-test"
